[package]
name = "church"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "front"
, "repl"]

[dependencies]

[dev-dependencies]

[features]
aliased-vars = []

default = ["aliased-vars"]
