[package]
name = "front"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"
church = { path = ".." }
logos = "0.14.1"
once_cell = "1.19.0"
lalrpop-util = "0.21.0"

[build-dependencies]
lalrpop = "0.21.0"
